import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="flex justify-between">
					<p>PizzUNI</p>
					<ul className="flex gap-4">
						<li>
							<a href="#sobre-nosotros">Sobre nosotros</a>
						</li>
						<li>
							<a href="#menu">Conoce nuestra carta</a>
						</li>
						<li>
							<a href="/chatbot">Chatea con nosotros</a>
						</li>
					</ul>
				</nav>
				{children}
			</body>
		</html>
	)
}
